# Generated by Django 3.2 on 2021-05-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField()),
                ('rule_type', models.IntegerField()),
                ('set_rule', models.BooleanField()),
                ('balance', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('descr', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.IntegerField()),
                ('transaction_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('processing_date', models.DateTimeField()),
                ('balance', models.FloatField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('descr', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('rule', models.IntegerField()),
            ],
        ),
    ]
