# Generated by Django 3.2.1 on 2021-05-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_auto_20210506_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('is_true', models.BooleanField()),
                ('direction', models.BooleanField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IsDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposits', models.CharField(max_length=2)),
                ('is_true', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Large_withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('is_true', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Low_funds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('is_true', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='CommerceUser',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
