# Generated by Django 3.2.1 on 2021-05-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_auto_20210507_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceNotif',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_true', models.CharField(max_length=1)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'balance_notif',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepositNotif',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_true', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'deposit_notif',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalNotif',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_true', models.CharField(max_length=1)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'withdrawal_notif',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Deposit_notification',
        ),
        migrations.DeleteModel(
            name='IsDeposit',
        ),
        migrations.DeleteModel(
            name='Large_withdraw',
        ),
        migrations.DeleteModel(
            name='Low_funds',
        ),
    ]
